import { defineField, defineType } from 'sanity';

import { evidenceFields } from './evidence';

export const architectureOverview = defineType({
  name: 'architectureOverview',
  title: 'Architecture Overview',
  type: 'document',
  fields: [
    defineField({
      name: 'repository',
      title: 'Repository',
      type: 'reference',
      to: [{ type: 'repository' }],
    }),
    defineField({ name: 'title', title: 'Title', type: 'string' }),
    defineField({ name: 'summary', title: 'Summary', type: 'text' }),
    defineField({
      name: 'components',
      title: 'Components',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({ name: 'dataFlows', title: 'Data Flows', type: 'text' }),
    defineField({
      name: 'setupInstructions',
      title: 'Setup Instructions',
      type: 'text',
    }),
    defineField({ name: 'limitations', title: 'Limitations', type: 'text' }),
    defineField({ name: 'commitSha', title: 'Commit SHA', type: 'string' }),
    defineField({
      name: 'generatedBy',
      title: 'Generated By',
      type: 'string',
      options: { list: ['deterministic', 'llm'] },
    }),
    defineField({
      name: 'sourceEvidence',
      title: 'Source Evidence',
      type: 'array',
      of: [{ type: 'object', fields: evidenceFields }],
    }),
  ],
});
