import { defineField, defineType } from 'sanity';

import { evidenceFields } from './evidence';

export const knowledgeDocument = defineType({
  name: 'knowledgeDocument',
  title: 'Knowledge Document',
  type: 'document',
  fields: [
    defineField({
      name: 'repository',
      title: 'Repository',
      type: 'reference',
      to: [{ type: 'repository' }],
    }),
    defineField({ name: 'title', title: 'Title', type: 'string' }),
    defineField({
      name: 'documentType',
      title: 'Document Type',
      type: 'string',
      options: {
        list: ['repository-overview', 'architecture', 'source-evidence'],
      },
    }),
    defineField({ name: 'path', title: 'Artifact Path', type: 'string' }),
    defineField({ name: 'content', title: 'Content', type: 'text' }),
    defineField({ name: 'commitSha', title: 'Commit SHA', type: 'string' }),
    defineField({
      name: 'generatedAt',
      title: 'Generated At',
      type: 'datetime',
    }),
    defineField({
      name: 'generatedBy',
      title: 'Generated By',
      type: 'string',
      options: { list: ['deterministic', 'llm'] },
    }),
    defineField({ name: 'source', title: 'Source', type: 'string' }),
    defineField({ name: 'analysisId', title: 'Analysis ID', type: 'string' }),
    defineField({
      name: 'sourceEvidence',
      title: 'Source Evidence',
      type: 'array',
      of: [{ type: 'object', fields: evidenceFields }],
    }),
  ],
});
